# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.
# If you have a load-balancing Redmine cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
# Be sure to restart your server when you modify this file.
RedmineApp::Application.config.secret_token = ENV['SECRET_KEY_BASE'] || ENV['SECRET_TOKEN'] || 'fallback_secret_key_that_is_at_least_30_chars_long_12345'
