production:
  access_key_id:      <%= ENV['S3_KEY'] %>
  secret_access_key:  <%= ENV['S3_SECRET'] %>
  bucket:             <%= ENV['S3_BUCKET'] %>
  endpoint:
  secure:
  private:            true
  expires:

development:
  access_key_id:
  secret_access_key:
  bucket:
  endpoint:
  secure:
  private:            true
  expires:
